### ISSUE TITLE
APP测试任务

### ISSUE THREAD

**Issue by fishtobeonthetree** [fishtobeonthetree/yihuo#11]

**Comment by buaaxm** [comment]
12.26  应用测试——客户端
用时：1小时

简单介绍：因我们开发的是安卓应用，而我的手机是ios系统，所以，我从同学那里借来了两部安卓手机做易货的测试。我按两个思路展开。第一：测试各个功能的稳定性，方法是每个功能都连续使用多次。
第二：测试应用的流畅性，方法是快速点击不同的功能。
通过本次测试，我发现了应用的两个bug，虽然都是小问题，但也会影响用户的使用，产生较差的用户体验，所以，我第一时间将问题反映给我们团队的开发人员，并建议他们修改bug。
另一方面，这个过程很有趣，我收获了快乐。
